Notification settings
umkc-cs-451-2020-spring/semester-project-group-3 pull request #43
Opened 2020-04-29 21:05 UTC by clarson1229

2020-05-03 15:22 UTC, sfeye reviewed
Nice 😎

2020-05-03 15:22 UTC, sfeye approved these changes

2020-05-04 01:12 UTC, sfeye requested changes
No new notifications are popping up when adding transcations

2020-05-04 15:55 UTC, lvolkmann approved these changes
Looks good! Finally about finished!

2020-05-04 16:37 UTC, sfeye approved these changes

2020-05-04 18:32 UTC, merged